sudo: required

jdk:
  - openjdk11

branches:
  only:
  - master
  - "/20(1[7-9]|2[0-9])[0-1][0-9][0-3][0-9]/"

services: docker
install: true
language: C

env:
  global:
  - ROUTERS=hb
  - ORG=mfdz

cache:
  directories:
  - $HOME/.m2

script: "./travis-build.sh"
